### ISSUE TITLE
md-02-assignments-juaenlkes - Error: Object 'Gapminder' not found

### ISSUE THREAD

**Issue by juaenlkes** [ds4owd-001/md-02-assignments-juaenlkes#1]
Hi @larnsce @mianzg @sskorik01, 

I would kindly request your help with the following issue: 
For the homework, I could only load the packages by changing the first code chunk as follows:
`{r}
#| label: load-packages
install.packages("gapminder")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("readr")
install.packages("sf")
install.packages("rnaturalearth")
library(gapminder)
library(ggplot2)
library(dplyr)
library(readr)
library(sf)
library(rnaturalearth)`

Still, when I try to progress running the second code chunk: 

`{r}
#| eval: true
 
gapminder_2007 <- gapminder |> 
  filter(year == 2007)`

I am getting the Error: "object 'gapminder_2007' not found".
Could you please provide a hint on how to proceed here?

Thanks in advance!
Jan

**Comment by larnsce** [comment]
Thanks for your question @juaenlkes. Is it possible that you have cloned the repository from GitHub to "Your Workspace" posit.cloud instead of the workspace for the course? What does it say on posit.cloud in the top-left next to md-02-assignments? 

<img width="686" alt="Screenshot 2023-11-13 at 23 00 54" src="https://github.com/ds4owd-001/md-02-assignments-juaenlkes/assets/18212549/18915d7e-975a-4df6-8291-8cf80219fc06">

**Comment by juaenlkes** [comment]
Thanks @larnsce . This exactly was the issue - the step was even explained in the instructions, but i somehow missed it. 
On another note, unfortunately I will not be able to join the session today due to conflicting appointments - I hope it is okay if I join the thursday session instead.

**Comment by larnsce** [comment]
Great, I am happy that it worked out for you now.

No worries about missing class today, I will create all assignments for you and you can try to catch up.
