### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by juaenlkes** [ds4owd-001/md-02-assignments-juaenlkes#2]
Hi @larnsce @mianzg @sskorik01,

thanks for the challenging task - I managed to get through most of it, however struggle with task 12. 
The content was alright, but I could not navigate editing the code, as backspace, delete, and typing seemed to randomly erase letters that were already written. Other than that, it has not happened when editing / working on any other code chunk.

Also, how do I reverse changes I made within a code chunk (the equivalent of ctrl + z)?

Thanks in advance!

Unfortunately, I will not be able to join today's session due to conflicting appointments; I will join thursday's session after re-working today's slides. 

Best, 
Jan

**Comment by sskorik01** [comment]
Hi Jan, 

Congratulations for working through the assignments! However, you haven't committed your code (your code in md-02a-data-visualization.qmd has not been updated on GitHub). You have to commit and push from Posit.cloud to confirm you have finished your assignment.

Concerning your deleting issue, I'm not sure what happened, expecially if it's only on this code chunk. To reverse change you can also use ctrl + z in posit.cloud. Let me know if you have any other questions!

Best, 
Sophia

**Comment by juaenlkes** [comment]
Hi Sophia, 

thanks for your feedback!
I have tried to commit/push the code now, but receive the following error:
"
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/ds4owd-001/md-02-assignments-juaenlkes.git/'

I enter my username juaenlkes and as password my GitHub PAT, but it just does not seem to go through. 
Any advice?

Thanks in advance!
Jan

**Comment by larnsce** [comment]
Thank you, @juaenlkes. You are doing this correctly, but from where do you copy your PAT? The response you get is an indication that the PAT you pasted is incorrect, and that often happens when you store it in a document like MS Word (.docx), as whitespace is copied when you highlight the PAT. 

Three approaches:

To be sure, I recommend you setup a new GitHub PAT following the instructions from Module 1. Then:

- Use a Password Manager to store your PAT (e.g. Chrome & Firefox have a built-in password manager where you could store your credentials) and then call your PAT from there
- Use Notepad on Windows to store your PAT
- Use another text editor on Mac (e.g. Sublime Text), anything that stores a file as plain text (.txt)

**Comment by sskorik01** [comment]
Hey Jan, does it work now?
